sudo: required
services:
  - docker

before_install:
  - docker build -t kckam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kckam/react-test npm test -- --watchAll=false

after_success:
  - docker build -t kckam/multi-client ./client
  - docker build -t kckam/multi-nginx ./nginx
  - docker build -t kckam/multi-server ./server
  - docker build -t kckam/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kckam/multi-client
  - docker push kckam/multi-nginx
  - docker push kckam/multi-server
  - docker push kckam/multi-worker
